### ISSUE TITLE
License

### ISSUE THREAD

**Issue by RustyMods** [shudnal/Seasons#1]
Reminder: your not allowed to publish on your own.

This is my mod and needs to be under my name. I'm happy for you to contribute and I will give you credit.

You can modify and use for yourself. But do not compete  with me please.

**Comment by shudnal** [comment]
I made this one completely by myself as you can see by commits history. I did not steal any code either.
Also the general approach is not concurrent. My mod doesn't and won't allow external textures.

**Comment by shudnal** [comment]
Also you officially have my permission to use anything you want from that repository.

**Comment by shudnal** [comment]
You may also want to use https://docs.unity3d.com/ScriptReference/MaterialPropertyBlock.html instead of SetTexture which can leads to potential memory leaks.

**Comment by RustyMods** [comment]
Thank you. Honestly, your act of publishing without even consulting me is what has me fired up.

I appreciate your willingness to share your work. But I do not appreciate, and do not condone your behavior of publishing without my consent.

This is a violation of my idea and my forthrightness to collaborate with you. I feel betrayed. 

I want to be clear. I am very happy to bring about a lawsuit against you.

**Comment by shudnal** [comment]
You must be joking rn. The idea of seasons had been on valheim reddit at least 2 years ago. That's not your own idea.
At first I wanted to contribute and even did 1 PR but I didn't like the general way of your implementation and had to make my own mod to meet my own goals. I don't know what info exactly you need to suit me but I will get you all the info you want.

**Comment by RustyMods** [comment]
I was happy to let you make your own and publish. As long as you asked. But you didn't. You went ahead and published.

So now I'm mad and ready to take action. Because you punched me in the gut.

**Comment by CheckYourFax** [comment]
Just because you're the first person that made a mod that has the idea seasons in it, doesn't mean you now own the idea of seasons in a game. 

There are thousands of games with seasons in it and you do not own the idea unless you can show a valid patent that says otherwise, which you don't. 

And don't say copyright, because copyright does not apply to ideas alone, that's what patents are for.
