### ISSUE TITLE
Creating new custom settings will get overwritten every single time when server is restarted.

### ISSUE THREAD

**Issue by anoxia1103** [shudnal/Seasons#10]
I tried doing it on local and on our server, but it seems that every single restart it overwrites the things I had already edited. Are there any options to do? I tried doing it while the server is on or my client it won't register the save commands.
[LogOutput.log](https://github.com/shudnal/Seasons/files/14495253/LogOutput.log)

**Comment by anoxia1103** [comment]
Unfortunately for our serverside log is not accessible via Valhost.net hoster.

**Comment by shudnal** [comment]
You edit the files with default settings which are indeed overwritten on every login.
You should copy file from Defaults folder to parent folder. For general settings it's /BepInEx/config/shudnal.Seasons
