### ISSUE TITLE
Grave Marker on Frozen Ocean

### ISSUE THREAD

**Issue by Morpheus1101** [shudnal/Seasons#14]
During winter, if your crossing the ocean or deep enough water and you die, it places the marker for your death under the ice with no way to recover it untill the ice thaws.  An added command to perhaps skip season or something would be handy as i dont believe the base game recognises the water is actually frozen per say.

**Comment by shudnal** [comment]
That's actually an oversight. I haven't died on the frozen ocean yet.
You can override current season with ease using config values located in "Season - Override" section.
I'll fix tombstone position in the next version. Though it will be in an Ashlands one.

**Comment by shudnal** [comment]
Thanks for discovering that issue. I've got it fixed in upcoming Ashlands version.

**Comment by Morpheus1101** [comment]
Out of curiosity, was this fixed in the updated vers for Ashlands?

**Comment by shudnal** [comment]
Yes as I told.
