### ISSUE TITLE
NullRefrenceException -- Seasons.WaterVolume_Awake_WaterState.Postfix

### ISSUE THREAD

**Issue by Morpheus1101** [shudnal/Seasons#15]
While setting up a new pack an starting a new world, this reference error cropped up a few times.

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
Seasons.WaterVolume_Awake_WaterState.Postfix (WaterVolume __instance) (at <145700a5d9374446bd6d0087403e7366>:0)
(wrapper dynamic-method) WaterVolume.DMD<WaterVolume::Awake>(WaterVolume)
UnityEngine.Object:Instantiate(GameObject, Vector3, Quaternion)
ZoneSystem:SpawnZone(Vector2i, SpawnMode, GameObject&)
ZoneSystem:CreateGhostZones(Vector3)
ZoneSystem:Update()

**Comment by shudnal** [comment]
Do you use proper version? That error is known for using regular version in Ashlands.
If you get this in Ashlands version then I need your log with Seasons config Logging enabled.

**Comment by Morpheus1101** [comment]
Im using the regular non Ashlands Beta version. Im using a pre-made pack called EpicValheim which consistently triggers that error every timer when creating a new world.  I have logging enabled an re-created a new world.

**Comment by shudnal** [comment]
Pls tell me if I got you correctly. The error only happens on first login into newly created world and next login doesn't trigger that.
If that so I made some refinements in the next version.

**Comment by Morpheus1101** [comment]
Unf its a persistent issue when moving around the map or re-joining the map...this seems to occur in Singleplayer consistently more so than Multiplayer on a Dedicated Server

**Comment by shudnal** [comment]
Ok then I need a log file with Logging enabled in Seasons.

**Comment by Morpheus1101** [comment]
LogOutPut.log or is yours called something specific ?

**Comment by Morpheus1101** [comment]
[LogOutput.log](https://github.com/shudnal/Seasons/files/15215269/LogOutput.log)

**Comment by shudnal** [comment]
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
StringExtensionMethods.GetStableHashCode (System.String str) (at <fd8aa8ac518244d290e57d530bf170fd>:0)
ExpandWorldData.LocationLoading+<>c.<UpdateHashes>b__21_0 (ZoneSystem+ZoneLocation loc) (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
System.Linq.Lookup`2[TKey,TElement].Create[TSource] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <2a397996daff412691ae4781443e8e88>:0)
System.Linq.Enumerable.ToLookup[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector, System.Collections.Generic.IEqualityComparer`1[T] comparer) (at <2a397996daff412691ae4781443e8e88>:0)
System.Linq.Enumerable.ToLookup[TSource,TKey,TElement] (System.Collections.Generic.IEnumerable`1[T] source, System.Func`2[T,TResult] keySelector, System.Func`2[T,TResult] elementSelector) (at <2a397996daff412691ae4781443e8e88>:0)
ExpandWorldData.Helper.ToDict[T,K,V] (System.Collections.Generic.IEnumerable`1[T] items, System.Func`2[T,TResult] key, System.Func`2[T,TResult] value) (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
ExpandWorldData.LocationLoading.UpdateHashes () (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
ExpandWorldData.LocationLoading.Load () (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
ExpandWorldData.LocationLoading.Initialize () (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
ExpandWorldData.InitializeContent.Postfix () (at <8ed994ad47c24e27948cf4f0d7810a12>:0)
(wrapper dynamic-method) ZoneSystem.DMD<ZoneSystem::Start>(ZoneSystem)

**Comment by shudnal** [comment]
That's the error from other mod preventing Seasons from initializing.

**Comment by shudnal** [comment]
Also you have a bunch of other errors. Not affecting Seasons though.
I've added a bulletproof againt similar errors. But even without error popping the Seasons will not work at all if there are any errors in ZoneSystem.Start method from other mods.

**Comment by shudnal** [comment]
After fixing the said error everything should be fine.
