### ISSUE TITLE
Stuck in between seasons

### ISSUE THREAD

**Issue by kittycat377** [shudnal/Seasons#19]
Hello!   Have fallen in love with this mod, but have had a recent issue when I updated the server to 1.3.11 from 1.3.7.   We were in the middle Winter and all of a sudden upon logging in we were at "Spring day 0" and it hasn't moved in over 7 in game days.   If I load in on a personal world the mod works as intended but can't get it to work on the dedicated even with multiple fresh downloads.

**Comment by shudnal** [comment]
Any errors in server's log file?

**Comment by kittycat377** [comment]
WARNING: Shader Unsupported: 'Custom/Water' - All subshaders removed
WARNING: Shader Did you use #pragma only_renderers and omit this platform?
WARNING: Shader If subshaders removal was intentional, you may have forgotten turning Fallback off?

i'm getting this message about 300 times with varying titles in the "custom/water" area

**Comment by kittycat377** [comment]
So i will be closing this issue,  Turns out it was an issue with the server provider!  When I updated the mod and restarted the server the server host company also did an update which turned off the Bepinex auto update.   This in turn broke the mod.

**Comment by shudnal** [comment]
Thanks for report. Glad to hear it wasn't actual issue!
