### ISSUE TITLE
Torch not working as FIre Source

### ISSUE THREAD

**Issue by mobiobione** [shudnal/Seasons#2]
Hi, not sure what's wrong, I haven't changed any code or settings, but the torch doesn't seem to be working as a fire source. Maybe conflicting with my other mods?

Awesome mod either way. Thank you for the amazing work.

![Screenshot 2024-01-17 205542](https://github.com/shudnal/Seasons/assets/39711291/ebfd14ff-167b-4631-8a81-dc4e7d0f7c02)
![Screenshot 2024-01-17 205534](https://github.com/shudnal/Seasons/assets/39711291/348a2004-7097-46e0-bc68-38a66d0a524e)
![Screenshot 2024-01-17 205525](https://github.com/shudnal/Seasons/assets/39711291/7b89def4-70de-4140-a1df-fa89056ebf8c)

**Comment by mobiobione** [comment]
Ah! When you said 'torch' I mistakenly assumed 'standing torch', (the standing torch is a heat source in Ark)
So everything works fine when I actually do what you said, and used the torch, not the standing torch.

Thanks again

**Comment by shudnal** [comment]
I've considered patching standing torches but it doesn't have any purpose atm. You can do it with another mod if you want.
Now only standard torch and goblin torch are being patched.
