### ISSUE TITLE
Upon migrating to a dedicated server, mod seems to be getting stuck perpetually attempting to update the season, sending the same message to the console repeatedly.

### ISSUE THREAD

**Issue by miss-mania** [shudnal/Seasons#22]
It will just endlessly output  "[Info   :   Seasons] Season update pending: Spring -> Spring, Day: 0 -> 13" into the log, and changing settings doesn't seem to be able to fix it.

**Comment by shudnal** [comment]
All I know atm is there was some similar issue in https://github.com/shudnal/Seasons/issues/21
And evidently it fixed itself somehow. 
I had no luck reprodicing it on my side so I think there is some issue with ServerSync unable to push custom value to the clients.
Looks like some hidden incompatibility issues with some other mod.

It could help if you provide a log file with logging enabled
**General - Logging enabled** -> **true**
**Test - Log time** -> **true**
