### ISSUE TITLE
Default stats.json file resets itself on world start

### ISSUE THREAD

**Issue by mdf25** [shudnal/Seasons#24]
Tried to change some configs in the Default stats.json and when I load Valheim and laod a world up again, it reverts any changes I have made to the file.

I wanted to remove the +10/+15 to the skills in each season whilst retaining the multiplier bonus. I tried
Test 1:
```
"m_skillLevels": {
  "Jump": 0.0,
  "Sneak": 0.0,
  "Run": 0.0,
  "Swim": 0.0
},
```

Test 2:
```
"m_skillLevels": {},
```

Test 3:
```
"m_skillLevels": {
  "Jump": 1.0,
  "Sneak": 1.0,
  "Run": 1.0,
  "Swim": 1.0
},
```

In all cases the file wouldn't keep the changes and reverted back to the default.\

I have also tried this on new worlds with a fresh character.

**Comment by shudnal** [comment]
That's because you are not meant to change Defaults. As it stated in the mod description
```To start making custom changes you should copy the corresponding file to config folder "shudnal.Seasons". When you change the file there should be "[Info : Seasons] Settings updated: Season_Name" line in the bepinex console and LogOutput.log file.```

**Comment by mdf25** [comment]
Ah I got it. Sorry for the bother :)
