### ISSUE TITLE
Feature request: Bog witch seasonal trading enabled

### ISSUE THREAD

**Issue by mdf25** [shudnal/Seasons#25]
Hi there,

I've been messing with the trader stock per season and for Haldor and Hildir it works out great. However for the Bog Witch, I can't get my seasonal items to show up in her inventory.

Here's what I tried in the Spring entries with just the bog witch on her own (assuming we have to use the lowercased prefab name like with haldor and hildir:
```json
{
    "Spring": {
        "bogwitch": [
            {
                "prefab": "Resin",
                "stack": 1,
                "price": 5,
                "requiredGlobalKey": "defeated_gdking"
            }
        ]
    }
}
```
Not sure if I'm doing something wrong or if it's not yet implemented for her trade tables  I've also verified I have the correct global key set. :D

**Comment by shudnal** [comment]
It is supported but in current version you should set trader name in case sensitive manner like `BogWitch`. I will make in case insensitive in the next version thought I can't tell when it will come live.

**Comment by shudnal** [comment]
But after I've checked how it actually works it's already case insensitive. It worked for me:
```
  "Winter": {
    "bogwitch": [
      {
        "prefab": "Pukeberries",
        "stack": 10,
        "price": 200,
        "requiredGlobalKey": ""
      }
    ]
  }
```

**Comment by mdf25** [comment]
Weird, it worked for me with the capitalization  but not without. Ah well, I got it working my end :D
