### ISSUE TITLE
Winter - Brightness during sunny periods

### ISSUE THREAD

**Issue by kingkylus** [shudnal/Seasons#3]
Hello, during winter season in sunny areas the floor is extremely bright, unplayable on a beach in meadows for example.

Any tips on how to fix?

**Comment by shudnal** [comment]
You can lower day luminance in winter or whole lightIntensityDayMultiplier by some degree. But pls be aware it could need some time for game to interpolate environments to see changes if you are applying them first time.

btw: White snow surface reflecting more light is not the feature I've built. It's how the game and IRL works.
