### ISSUE TITLE
compatibility issue

### ISSUE THREAD

**Issue by Maxphog** [shudnal/Seasons#4]
mod name: Foraging v1.0.8
mod author:  Smoothbrain
mod link: https://valheim.thunderstore.io/package/Smoothbrain/Foraging/

![image](https://github.com/shudnal/Seasons/assets/113948291/686e282e-406c-4179-aa43-4d2a9f7e07b1)

issue: foraging skill effects and buffs that affect amount of drops are picked from ground pickable foods is overwritten by the seasons mod. 

replication method: 

1. hop on a world with the two mods enabled
2. open dev commands
3. spawn a berry bush
4. raise you foraging skill by like a couple dozens with the command `raiseskill Foraging 24 `
5. pick a berry. 

Expected result: should at least get more than 2 or 3 berries from a single berry bush if your foraging skill is higher.

actual result: you actually only receive one berry.

tested with 4 different berry bushes and a Foraging skill level higher than 30.

![image](https://github.com/shudnal/Seasons/assets/113948291/8caf25be-20e0-4142-b075-1cf997e92bc4)

![image](https://github.com/shudnal/Seasons/assets/113948291/0737fc4d-0deb-4def-bfcf-6cb018501aaf)

**Comment by Maxphog** [comment]
hows my doc shudnal?

**Comment by shudnal** [comment]
I've checked the Foraging code and couldn't find any incompatibilities except maybe potential wrong estimate of pickable respawn time.

I've tried to reproduce it by your steps and it was working just fine. I've been getting as much berries as it should be due to Foraging skill level and config settings.

**Comment by Maxphog** [comment]
update! You are correct recreating it this time with a skill lvl of 100 and i get twice the amount of berries as expected by the foraging cfg settings from unspawned-by-commands berry bushes initially generated around spawn. so i'm guessing it mightve been another one of my other installed mods fudging the drop rolls.... so ill hunt it down TY SHUD.  😄
