### ISSUE TITLE
Global keys not being set for seasons

### ISSUE THREAD

**Issue by mdf25** [shudnal/Seasons#5]
Using only the Seasons mod and ServerDevcommands in a test playthrough, I have enabled the Global Keys section in the configuration and changed the names to lowercase as such:

```
[Seasons - Global keys]

## Enables setting seasonal global key
# Setting type: Boolean
# Default value: false
Enable setting seasonal Global Keys = true

## Seasonal global key for automn
# Setting type: String
# Default value: Season_Fall
Fall = season_fall

## Seasonal global key for spring
# Setting type: String
# Default value: Season_Spring
Spring = season_spring

## Seasonal global key for summer
# Setting type: String
# Default value: Season_Summer
Summer = season_summer

## Seasonal global key for winter
# Setting type: String
# Default value: Season_Winter
Winter = season_winter
```

When I spawn into a world I use the command `listkeys` and I get the following output:
```
Current Keys: 0
Server Option Keys: 0
Player Keys: 1
```
but Player Keys is empty and doesn't show a name (guessing a blank string)

However after doing `setkey season_spring` I get
```
Current Keys: 1
  season_spring
Server Option Keys: 0
Player Keys: 1
```

So, I think the global keys part is not working - sort of. Was hoping to use it together with SpawnThat! to change what spawns during a season.

I have also tried with default keys (capitalized) and with a fresh player and world. No luck either :)

Took a look at the DLL and I think I found the issue, or maybe an idea - wondering if on first world creation/load it doesn't perform the `OnSeasonChange()` event to set the key. Maybe when world is first created it should check the season after `ZNetScene.Awake()`.

I tested gameplay and when the season changes, it does indeed give the correct global key. So, the problem is only related to the very first spring when the world is created and player spawns. And possibly if the mod is installed after a world has been created, it only applies the key after the first season change and not when it's first installed and applied to that world / server.

**Comment by shudnal** [comment]
That's correct. I've added setting seasonal key to day change. I think having a fresh world in day 1 with no season_spring key is not a big deal.
For test purpose you can easily toggle season override to get key set.

Btw keys are case-insensitive as that's the way they saved in the game.

**Comment by mdf25** [comment]
Shame it won't get a patch, was hoping to have some extra spring spawns in first year to spice up the experience a bit. Guess I can change the odinhorse and black deer spawns to summer instead to get around it and by the time player is in swamp they'll see new changes in spring 2 :)
