### ISSUE TITLE
Caching in the BepInEx Config folder

### ISSUE THREAD

**Issue by yayoranges** [shudnal/Seasons#6]
Issue: 
- Caching files inside 'BepInEx/Config' breaks Thunderstore profile code generation

Replication Steps:
1. Using Thunderstore or R2Modman and a fresh Valheim profile with 0 mods
2. Download Seasons mod with manager
3. Navigate to 'Settings > Export Profile as a Code' and click the button 1 time
4. A window pops up displaying our new profile code
5. Run Valheim to generate mod config files & load into any world to build cache
6. Close Valheim
7. Navigate to 'Settings > Export Profile as a Code' and click the button 1 time

Expected Result:

- A window pops up displaying our new profile code

Actual Result:

- After 45 seconds an Error window will appear with HTTP code 413

Notes:
Profile codes sync mods and configuration files, please consider moving the caching folder out of 'BepInEx/Config'
Thank you for sharing this mod!

**Comment by shudnal** [comment]
That's reasonable. I'll put cache revisions in 'BepInEx/Cache' folder in the next version in a couple of days.

**Comment by yayoranges** [comment]
Excellent, and thank you for the quick response.

**Comment by shudnal** [comment]
Cache was moved in current 1.1.1 version.

**Comment by shudnal** [comment]
You need to delete Cache folder from current config folder manually.
