### ISSUE TITLE
Dying from Winter freezing anywhere

### ISSUE THREAD

**Issue by willcp10** [shudnal/Seasons#9]
Dying from Winter Freezing anywhere anytime, even with config enabled.
![image](https://github.com/shudnal/Seasons/assets/73892118/095416ce-53a7-4ebe-9443-5c9c48705078)

**Comment by willcp10** [comment]
Suggestion:

Remove + 0.1f from condition, kills if player has exactly 1hp.
![image](https://github.com/shudnal/Seasons/assets/73892118/d875256c-a87a-4468-8ccb-8ec8ceb5d9e8)

**Comment by shudnal** [comment]
That's reasonable.

**Comment by shudnal** [comment]
Will be fixed in 1.1.2 soon.
